### ISSUE TITLE
Trouble in executing problem

### ISSUE THREAD

**Issue by khurrumsaleem** [openmsr/pincell_msr#1]
Hye,

I tried to execute the problem by installing the relevant "MSR" branch.  but I cannot complete it due to an error. 

Traceback (most recent call last):
  File "/mnt/e/Work/openmsr/example/example.py", line 3, in <module>
    import openmc.deplete
  File "/home/aayan/miniconda3/envs/openmsr/lib/python3.9/site-packages/openmc/deplete/__init__.py", line 11, in <module>
    from .coupled_operator import *
  File "/home/aayan/miniconda3/envs/openmsr/lib/python3.9/site-packages/openmc/deplete/coupled_operator.py", line 21, in <module>
    import openmc.lib
  File "/home/aayan/miniconda3/envs/openmsr/lib/python3.9/site-packages/openmc/lib/__init__.py", line 32, in <module>
    _dll = CDLL(_filename)
  File "/home/aayan/miniconda3/envs/openmsr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/aayan/miniconda3/envs/openmsr/lib/python3.9/site-packages/openmc/lib/libopenmc.so: cannot open shared object file: No such file or directory

can you have a guess what it might be due to?

**Comment by church89** [comment]
Hi,
Nice to see that you're interested!  
For what I can see it seems that  is not finding the shared library, can you import openmc.lib from another branch of openmc or it gives you the same error? Also, what version of openmc did you install?

**Comment by khurrumsaleem** [comment]
thankyou very much @church89 for getting back to my message. I recompiled the code and it is working fine now. I will close the issue now. thanks again.
